### ISSUE TITLE
Failure establishing SSH session

### ISSUE THREAD

**Issue by jowparks** [dylankenneally/react-native-ssh-sftp-example#2]
- I installed this repo with `npm i`
- Couldn't build for simulator because of error:
```
Building for 'iOS-simulator', but linking in object file (/Users/joe/repos/react-native-ssh-sftp-example/ios/Pods/NMSSH/NMSSH-iOS/Libraries/lib/libcrypto.a[arm64][2](cryptlib.o)) built for 'iOS'
```
Guessing this is because I am running on M1 MBP.

When I built on for my phone directly it runs but I get the error when connecting:
```
NMSSH: libssh2 (v1.8.0) initialized
NMSSH: Start ec2-35-80-15-73.us-west-2.compute.amazonaws.com resolution
NMSSH: Socket connection to 35.80.15.73 on port 22 succesful
NMSSH: Failure establishing SSH session
Connection to host ec2-35-80-15-73.us-west-2.compute.amazonaws.com failed
NMSSH: Disconnected
```
Note that ssh from my local machine with same key or password works fine.

**Comment by raghulkrishna** [comment]
@jowparks  how did you fix this?

**Comment by jowparks** [comment]
https://github.com/dylankenneally/react-native-ssh-sftp/issues/11

**Comment by dylankenneally** [comment]
Resolved, thanks to @jowparks, see [this comment](https://github.com/dylankenneally/react-native-ssh-sftp/issues/11#issuecomment-2024205839)
